---
#
# Playbook to install collectd on undercloud/overcloud
#
# Install on all undercloud/overcloud machines:
# ansible-playbook -i hosts install/collectd-openstack.yml
#
# Or use tags:
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "undercloud"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "controller"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "objectstorage"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "cephstorage"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "compute"
#


- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  vars:
    config_type: undercloud
  roles:
    - { role: common, when: collectd_undercloud }
    - { role: epel, when: collectd_undercloud }
    - { role: collectd-openstack, when: collectd_undercloud }
  tasks:
    - name: Collectd off if not collectd_undercloud
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_undercloud
      ignore_errors: true
  tags: undercloud

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: controller
  roles:
    - { role: common, when: collectd_controller }
    - { role: epel, when: collectd_controller }
    - { role: collectd-openstack, when: collectd_controller }
  tasks:
    - name: Collectd off if not collectd_controller
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_controller
      ignore_errors: true
  tags: controller

- hosts: objectstorage
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: objectstorage
  roles:
    - { role: common, when: collectd_objectstorage }
    - { role: epel, when: collectd_objectstorage }
    - { role: collectd-openstack, when: collectd_objectstorage }
  tasks:
    - name: Collectd off if not collectd_objectstorage
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_objectstorage
      ignore_errors: true
  tags: objectstorage

- hosts: cephstorage
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: cephstorage
  roles:
    - { role: common, when: collectd_cephstorage }
    - { role: epel, when: collectd_cephstorage }
    - { role: collectd-openstack, when: collectd_cephstorage }
  tasks:
    - name: Collectd off if not collectd_cephstorage
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_cephstorage
      ignore_errors: true
  tags: cephstorage

- hosts: compute
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: compute
  roles:
    - { role: common, when: collectd_compute }
    - { role: epel, when: collectd_compute }
    - { role: collectd-openstack, when: collectd_compute }
  tasks:
    - name: Collectd off if not collectd_compute
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_compute
      ignore_errors: true
  tags: compute
