---
- hosts: localhost
  connection: local
  tasks:
  - name: find local ssh keys
    find: path='./' patterns='id_rsa.*'
    register: ssh_found
  - name: create ssh key
    command: ssh-keygen -t rsa -N '' -f id_rsa
    run_once: true
    delegate_to: localhost
    ignore_errors: yes
    when: ssh_found.matched == 0

- hosts: all
  become: true
  become_user: root
#  vars:
#   domain: opsits.com
  tasks:
  - name: create and update ssh for shared communications
    include: tasks/ssh.yml
  - name: ensure hosts file is correct
    include: tasks/hosts.yml
  - name: ensure resolve has search for domain
    include: tasks/resolve.yml
  - name: upload files
    copy: src={{item}} dest=/root/{{item}} mode=0755
    with_items:
      - add_flavor.sh
      - centos.sh
      - centos-cmp.sh
      - post-install.sh
      - setup_network.sh
      - multinode.sh
      - import_image.sh
      - node_delete.sh
      - launch.sh
      - multinode
  - name: run pre-install script control
    command: ./centos.sh
    when: inventory_hostname in groups['control']
  - name: run pre-install script compute
    command: ./centos-cmp.sh
    when: inventory_hostname in groups['compute']
  - name: launch openstack with kolla
    command: kolla-ansible -i multinode deploy
    register: deploy_multinode
    ignore_errors: true
  - name: run post-install config
    command: ./post-install.sh
    register: post_install
    ignore_errors: true
  - name: enable masquerade (NAT) on external interface
    include: tasks/masq.yml
