---
#
# Install/run collectd for Browbeat
#

#
# (akrzos) yum module works at this point due to the fact the EPEL repo now exists.  EPEL rpm is
# installed at this point in time.
#
- name: Install collectd rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - collectd
    - collectd-turbostat
    - collectd-mysql

# Get mysql's root password
- name: (Controllers Only) Get mysql root password
  command: hiera mysql::server::root_password
  become: true
  register: mysql_root_password
  when: "'controller' in group_names"

- name: Get overcloudrc
  remote_user: "{{local_remote_user}}"
  shell: "cat /home/stack/overcloudrc | grep 'OS' | awk '{gsub(/export /,\"Environment=\");print }'"
  delegate_to: "{{groups['undercloud'][0]}}"
  register: overcloudrc_file
  when: "(gnocchi_status_python_plugin == true) and (inventory_hostname == groups['controller'][0])"

- name: Add environment variables to collectd.service systemd file
  become: true
  lineinfile:
    dest: /usr/lib/systemd/system/collectd.service
    insertafter: '\[Service\]'
    line: "{{item}}"
  with_items: "{{overcloudrc_file.stdout_lines | default(omit)}}"
  when: "(gnocchi_status_python_plugin == true) and (inventory_hostname == groups['controller'][0])"

- name: Reload systemd units
  command: systemctl daemon-reload
  become: true
  when: "(gnocchi_status_python_plugin == true) and (inventory_hostname == groups['controller'][0])"

- name: Configure collectd.conf
  template:
    src: "{{config_type}}.collectd.conf.j2"
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy collectd_gnocchi_status.py
  copy:
    src: collectd_gnocchi_status.py
    dest: /usr/local/bin/collectd_gnocchi_status.py
    owner: root
    group: root
    mode: 0755
  become: true
  when: gnocchi_status_python_plugin

#
# Configure selinux bits
#
- name: Check for collectd permissive
  shell: semodule -l | grep -q permissive_collectd_t
  become: true
  register: collectd_permissive
  ignore_errors: true
  changed_when: false

- name: Set permissive for collectd
  command: semanage permissive -a collectd_t
  become: true
  when: collectd_permissive.rc != 0

#
# Additional policy bits may be needed for exec
#
- name: Collectd policy customization
  copy:
    src: custom-collectd.pp
    dest: /root/custom-collectd.pp
    owner: root
    group: root
    mode: 0644
  become: true

- name: Check for collectd custom
  shell: semodule -l | grep -q custom-collectd
  become: true
  register: collectd_custom
  ignore_errors: true
  changed_when: false

- name: Set custom policy for collectd
  command: semodule -i /root/custom-collectd.pp
  become: true
  when: collectd_custom.rc != 0

#
# Start collectd service
#
- name: Setup collectd service
  service:
    name: collectd
    state: restarted
    enabled: true
  become: true
